<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BigBobChat.Core\BigBobChat.Core.csproj" />
    <ProjectReference Include="..\BigBobChat.Infrastructure\BigBobChat.Infrastructure.csproj" />
  </ItemGroup>

</Project>
